### ISSUE TITLE
Project still active?

### ISSUE THREAD

**Issue by neufeldtech** [bullywhippet/Android_Beer_Journal#3]
Hey, thanks for this project. Haven't seen any updates in a while, is it still active?

**Comment by bullywhippet** [comment]
Hey @neufeldtech thanks for your interest! This has not been maintained for a few years now. However I was contemplating repurposing it into a whiskey /scotch rating app, do you happen to know of any whiskey apis ?

**Comment by neufeldtech** [comment]
no
